services: docker

env:
  - NODE_ENV=test
before_install:
  - docker -v
  # Stop the postgres instance TravisCI sets up automatically
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop
  # Build the containers
  - docker-compose build
install:
  - docker-compose up -d
script:
  # Migrate and seed database
  - docker-compose exec web /bin/sh -c "npm run db:migrate"
  - docker-compose exec web /bin/sh -c "npm run db:seed"
  # Run tests
  - docker-compose exec web /bin/sh -c "npm run test"