version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=milkroad
      - POSTGRES_USER=postgres
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=milkroad
      - DB_USER=postgres
      - DB_PASS=
      - NODE_ENV