version: '2'
services:
  web:
    restart: always
    network_mode: "host"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "80:80"
    environment:
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASS
      - NODE_ENV=production